HOSTNAME: localhost
PORT: 8000
DB_HOST: localhost
DB_PORT: 5432
DB_USER: test
DB_PASSWORD: test
DB_DATABASE: test
DB_PATH: book/internal/model/migrations
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_NUM: 0
REDIS_DB_PASSWORD: